name: Sync to Hugging Face Space

on:
  push:
    branches:
      - deploy

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out GitHub code
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      # Step 2: Push that code to Hugging Face Space
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push https://NuranR:$HF_TOKEN@huggingface.co/spaces/NuranR/chesslens main
